spring:
  sql:
    init:
      mode: always
  datasource:
    username: stats
    url: jdbc:postgresql://localhost:5432/stats
    driverClassName: org.postgresql.Driver
    password: stats
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
server:
  port: '9090'