version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-server
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
